services:
  front:
    image: froissant/ideas-hackdays2025:front
    ports:
      - "0.0.0.0:3000:80"
    depends_on:
      - back
      - back-albert
  back:
    image: froissant/ideas-hackdays2025:back
    ports:
      - "0.0.0.0:3001:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - ASSET_DIR=./.temp/assets
      - ROOM_DIR=./.temp/assets
      - PROJECT_DIR="./.assets/projects"
      - MEMEGEN_API_URL=https://api.memegen.link
      - AI_API_URL=http://back-albert:8000
  back-albert:
    image: froissant/ideas-hackdays2025:back-albert
    expose:
      - "8000"
    ports:
      - "0.0.0.0:3002:8000"
